### ISSUE TITLE
pointer printing sanitization

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS-Archive/linux-hardened#16]

**Comment by sempervictus** [comment]
I think this is now "in progress elsewhere," yay. Thank you for tracking all of this.

**Comment by thestinger** [comment]
Yeah, just marked it as that a minute before you replied.

Note that I stopped tracking issues tied to GCC plugins here because Google is moving to Clang and since they're such a big part of the kernel hardening effort the writing is on the wall for GCC despite the history in PaX and grsecurity of GCC plugins.

**Comment by sempervictus** [comment]
Suppose that bodes well for kcfi and other complicated as a rubix dodecahedron functions. Thanks

**Comment by thestinger** [comment]
I've done compiler work on LLVM before and I'll be much happier working with that. From my perspective, Google dropping GCC for compiling the kernel as they've done for everything else can't come soon enough.

**Comment by thestinger** [comment]
Most compiler hardening can be shared between the kernel and userspace and GCC is already gone for the Android userspace.

**Comment by thestinger** [comment]
This is a mess upstream and I'm not following it anymore. I don't know what's happening with it.

**Comment by sempervictus** [comment]
Yeah, they're tossing around a bunch of scriptage and esoteric rigmarole about why production kernels need to leak sensitive data to enable use of dangerously implemented userspace functions... I think.
