### ISSUE TITLE
MODHARDEN

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS-Archive/linux-hardened#17]

**Comment by kees** [comment]
https://lkml.org/lkml/2017/4/19/1086

**Comment by thestinger** [comment]
Not currently in-scope.

**Comment by thestinger** [comment]
This is marked out-of-scope because the Android Open Source Project / CopperheadOS don't use modules. However, patches for this would be accepted as part of linux-hardened if someone else was willing to implement them and handle significant conflicts or other changes requiring the code to be extended / rewritten.

**Comment by thestinger** [comment]
Not going to be including this since Android doesn't have modules enabled at runtime even when they're used.
