### ISSUE TITLE
trusted path execution

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS-Archive/linux-hardened#33]
This is a very low priority for linux-hardened since SELinux can be used to provide the same functionality and more.

**Comment by cormander** [comment]
Hey all. I'm the author of [tpe-lkm](https://github.com/cormander/tpe-lkm/) and this was brought to my attention. I'm happy to contribute in some way. My first observation is the lack of hooking mmap and mprotect, see details in [tpe issue 25](https://github.com/cormander/tpe-lkm/issues/25).

**Comment by thestinger** [comment]
@cormander There's no TPE implementation included here yet. In CopperheadOS, SELinux is used for this so it's among the features that I don't consider high priorities along with MPROTECT and many of the other miscellaneous features.

**Comment by thestinger** [comment]
And I wouldn't really agree with this:

> a volunteer's project trying to mainline most grsecurity features

Landing features upstream isn't my goal but rather a means to an end. It means not needing to maintain code out-of-tree and getting more input into the changes.

**Comment by cormander** [comment]
I suppose I was looking at the PR#32. Ping me if this ever gets considered. Thanks.

**Comment by thestinger** [comment]
@cormander I'd like to include it in some form but I just haven't closely looked at it or thought about it much yet. The grsecurity restrict all option doesn't have a way to do exceptions but might be incompatible with how the app UID/GID model works on Android for some apps that check each other's signature / id and share code i.e. they act as a library. I'd want it to work for that case.

**Comment by cormander** [comment]
Not too long ago I coded in exceptions via xattr that can be set on files to work around that problem.

**Comment by thestinger** [comment]
Not currently in-scope.

**Comment by thestinger** [comment]
This isn't currently in-scope since SELinux can be used to provide the same protection and linux-hardened is intended to be used alongside SELinux or an equivalent rather than handling access control itself. There can be alternative options upstream as LSMs but it's not going to be done here.
