### ISSUE TITLE
Enable TOMOYO by default

### ISSUE THREAD

**Issue by x4rxes** [GrapheneOS-Archive/linux-hardened#39]
Used to be on linux-grsec.

**Comment by thestinger** [comment]
That's outside the scope of this project, it's a downstream packaging choice.

**Comment by dbaxa** [comment]
@thestinger do you consider enabling `yama` a downstream packaging choice as well?

**Comment by thestinger** [comment]
Yama doesn't require userspace integration. On the other hand enabling TOMOYO by default here wouldn't accomplish anything and doesn't make any sense. Regardless, changing the defaults here doesn't actively change downstream configuration and isn't important. It only impacts the *defaults* in freshly generated configuration, not a new configuration derived from a previous one. Configuration is always going to be a downstream choice. It isn't going to be forced unless there's truly no reason to have something available as a configuration option.

**Comment by Atavic** [comment]
Right, [TOMOYO](https://tomoyo.osdn.jp/), as any Mandatory Access Control, requires the active use of its Policy Editor:
the default profile "0", also known as "Disabled Mode", is completely unrestricted.
