### ISSUE TITLE
denyusb implementation

### ISSUE THREAD

**Issue by osteichthyes** [GrapheneOS-Archive/linux-hardened#47]
Not really an issue, more a request for clarification in the docs:

Is denyusb implemented with a sysctl like the grsec implementation was, if so what is the flag?

**Comment by thestinger** [comment]
The sysctl is `kernel.deny_new_usb` and there isn't a kernel configuration option. It was enabled with `CONFIG_USB` but now that's switched to `CONFIG_USB_SUPPORT` for the next release since `CONFIG_USB` is usually a module on traditional distributions so it wasn't being enabled there.
