### ISSUE TITLE
Longterm releases?

### ISSUE THREAD

**Issue by nullchinchilla** [GrapheneOS-Archive/linux-hardened#48]
I feel like a hardened version of longterm kernel releases would be very useful, as it then allows easy usage on systems such as Debian and Ubuntu LTS with conservative update schedules. Hardened kernels would be very useful on public servers, which tend to run conservative distros. Besides, longterm releases like 4.9.x and 4.4.x change slowly and publicly available grsec patches, so it'll probably be easier to port various features compared to doing the same thing on the quickly moving target that is the stable version.

**Comment by thestinger** [comment]
It's not within the current scope and there's no way it would happen with kernel branches older than the project. It started with 4.11. If and when there's a substantial amount of development happening here, splitting up resources across multiple branches can be considered. It's currently not very active.
