### ISSUE TITLE
[Patch attached] Secure TCP timestamp response

### ISSUE THREAD

**Issue by theLOICofFRANCE** [GrapheneOS-Archive/linux-hardened#50]
Hi,

The pentesters use the TCP timestamp response for fingerprinted based on the behavior and to find the remote host's uptime.

I suggest you change the default value (which should slightly increase the performance).

[tcp_timestamps_secure.txt](https://github.com/copperhead/linux-hardened/files/1204993/tcp_timestamps_secure.txt)

This is a simple alternative to Brad's "[random_timestamp.diff](https://grsecurity.net/~spender/random_timestamp.diff)" patch.

Thanks.

**Comment by thestinger** [comment]
Modern Linux kernels use a per-connection random base for the timestamps:

https://github.com/torvalds/linux/commit/95a22caee396cef0bb2ca8fafdd82966a49367bb

The main issue (TCP timestamps) is resolved in a generic way.

**Comment by theLOICofFRANCE** [comment]
Great, I hadn't seen it.
