### ISSUE TITLE
Why is AppArmor not enabled?

### ISSUE THREAD

**Issue by francoism90** [GrapheneOS-Archive/linux-hardened#67]
SELinux is, why not also enable AppArmor? :)

**Comment by thestinger** [comment]
This project doesn't enable or disable either AppArmor or SELinux. It's not something decided here.

It is true that linux-hardened will be developed solely with usage alongside a full system SELinux policy in mind. It won't be including features that can be implemented via SELinux policy so unfortunately you'll be missing out on many important security features without it.
