### ISSUE TITLE
zfs load-keys results in KP

### ISSUE THREAD

**Issue by francoism90** [GrapheneOS-Archive/linux-hardened#68]
I'm keep getting a KP when loading the zfs module on linux-hardened.
How could I provide you with debug info? I already tried rebuilding the kernel/using latest git.

On the default kernel it works without any issues.

Thanks!

**Comment by thestinger** [comment]
You can paste errors in code blocks or attach images here.

**Comment by thestinger** [comment]
Can you confirm if this still occurs for you on 4.14.13.a?

**Comment by francoism90** [comment]
@thestinger I'm sorry, no longer able to check this atm. Will close this bug and re-open if needed when I found the time to test. :)

Thanks for your time.
