### ISSUE TITLE
btrfs compressed root volume fails to boot

### ISSUE THREAD

**Issue by JSkier21** [GrapheneOS-Archive/linux-hardened#7]
I have a btrfs compressed root volume. When I try to boot it on the hardened kernel, it panics:

`Kernal panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
`
Using version 	4.11.e on ArchLinux; could be a 4.11 bug upstream now that I think of it. 

Will work on getting more info, end of trace (apologies, I need to get a better test environment, it's on a vps): 

![image](https://cloud.githubusercontent.com/assets/3190223/25960529/d352adb2-363c-11e7-95a1-7cf47592ff01.png)

**Comment by thestinger** [comment]
This is probably an upstream issue in 4.11, try building the linux-hardened package with the patch line disabled.

**Comment by JSkier21** [comment]
Thanks for your time and looking at this @thestinger. Arch is currently on 4.10, I'm working on compiling 4.11 w/o the patch. I'll close this for now, since it's extremely likely it's upstream; I also don't have this issue on ext4 and 4.11-hardened. Lastly, the fs tree and btrfs specifically had a bit of work done in 4.11.
