### ISSUE TITLE
Compiling error with version 4.14.13 to version 4.15.1

### ISSUE THREAD

**Issue by Kalle72** [GrapheneOS-Archive/linux-hardened#70]
Hello,

I get the following compiling error (vanilla-sources patched with the corresponding hardened-patch):

`Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler `
`make: *** [Makefile:1097: prepare-compiler-check] Error 1`

Interestingly, I get no error with the unpatched vanilla-sources or with gentoo-sources. (These kernels work well and  CONFIG_CC_STACKPROTECTOR_STRONG is set). Moreover, before 4.14.13 everything worked. 

Maybe the problem is gentoo's change from gcc-5.x to gcc-6.4.0

Kind regards 
Kalle

**Comment by pauleve** [comment]
You probably need to unset `CONFIG_LOCAL_SANITIZE`, I guess it is supported only by gcc > 7.something.

**Comment by chaoskagami** [comment]
Ran into this the other day. Turn off the option named something like "sanitize local".

It looks like the makefile doesn't check compiler support for fsanitize and fails at the first test which just so happens to be stack check.

On February 6, 2018 7:37:57 AM EST, Kalle72 <notifications@github.com> wrote:
>Hello,
>
>I get the following compiling error (vanilla-sources patched with the
>corresponding hardened-patch):
>
>`Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong
>not supported by compiler `
>`make: *** [Makefile:1097: prepare-compiler-check] Error 1`
>
>Interestingly, I get no error with the unpatched vanilla-sources or
>with gentoo-sources. (These kernels work well and 
>CONFIG_CC_STACKPROTECTOR_STRONG is set). Moreover, before 4.14.13
>everything worked. 
>
>Maybe the problem is gentoo's change from gcc-5.x to gcc-6.4.0
>
>Kind regards 
>Kalle
>
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/copperhead/linux-hardened/issues/70

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Kalle72** [comment]
Thanks to you both. Seems true. Problem solved

**Comment by thestinger** [comment]
It does say in the configuration option that it only works with Copperhead's hardened Clang toolchain. It could be switched to check for support but it should fail if it's configured and not present, not just ignore it.

**Comment by Bernhard40** [comment]
Does it mean it doesn't work with normal clang?

**Comment by thestinger** [comment]
It requires a patched Clang toolchain for now until it lands upstream which is planned.
